# 00. Les Bases de PyTorch

## Qu'est-ce que PyTorch ?

[PyTorch](https://pytorch.org/) est un framework open source d'apprentissage automatique et d'apprentissage profond.

## À quoi peut servir PyTorch ?

PyTorch vous permet de manipuler et de traiter des données et d'écrire des algorithmes d'apprentissage automatique à l'aide du code Python.

## Qui utilise PyTorch ?

Un grand nombre des plus grandes entreprises technologiques au monde telles que [**Meta** (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/ ), **Tesla** et **Microsoft** ainsi que des sociétés de recherche en intelligence artificielle telles que [**OpenAI**](https://openai.com/blog/openai-pytorch/) utilise PyTorch pour conduire de la recherche et intégrer l'apprentissage automatique dans leurs propositions de produits.

![pytorch utilisé dans l'industrie et la recherche](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png )

Par exemple, Andrej Karpathy (responsable de l'IA chez Tesla entre 2017 et 2022) a donné plusieurs conférences ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M ?t=2904)) sur la façon dont Tesla utilise PyTorch pour alimenter ses modèles de vision par ordinateur autonomes.

PyTorch est également utilisé dans d'autres secteurs tels que l'agriculture pour [alimenter la vision par ordinateur sur les tracteurs](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## Pourquoi utiliser PyTorch ?

Les chercheurs en apprentissage automatique adorent utiliser PyTorch. Et depuis février 2022, PyTorch est le [framework d'apprentissage profond le plus utilisé sur Papers With Code](https://paperswithcode.com/trends), un site Web permettant de suivre les articles de recherche sur l'apprentissage automatique et les référentiels de code qui leur sont associés.

PyTorch aide également à prendre en charge de nombreuses choses telles que l'accélération GPU (rendant votre code plus rapide) en coulisse.

Vous pouvez donc vous concentrer sur la manipulation des données et l'écriture d'algorithmes et PyTorch veillera à ce qu'il fonctionne rapidement.

Et si des entreprises telles que Tesla et Meta (Facebook) l'utilisent pour créer des modèles qu'elles déploient pour alimenter centaines applications, conduire des milliers de voitures et fournir du contenu à des milliards de personnes, cette bibliothéque python est clairement également performante sur le plan du développement pour une mutitude d'usage different.

## Ce que nous allons aborder dans ce module

Ce cours de **Deep Learning** est découpé en différentes sections (Jupyter Notebook).

Chaque Notebook couvrira des idées et des concepts importants dans PyTorch. Ce Notebook traite du conteneur élémentaire des données pour des fins d'apprentissage automatique et de d'apprentissage profond, i.e: ***le tenseur***.

Plus précisément, nous allons couvrir dans cette unité :

| **Sujet** | **Contenu** |
| ----- | ----- |
| **Introduction aux tenseurs** | Les tenseurs sont l’élément de base de tout l’apprentissage automatique et de l’apprentissage profond. |
| **Création de tenseurs** | Les tenseurs peuvent représenter presque tous les types de données (images, mots, tableaux de nombres). |
| **Obtenir des informations à partir des tenseurs** | Si vous pouvez mettre des informations dans un tenseur, vous souhaiterez également les extraire. |
| **Manipulation des tenseurs** | Les algorithmes d'apprentissage automatique (comme les réseaux de neurones) impliquent de manipuler les tenseurs de différentes manières, par exemple en ajoutant, en multipliant et en combinant. |
| **Gérer les formes tensorielles** | L'un des problèmes les plus courants dans l'apprentissage automatique est la gestion des inadéquations de forme (en essayant de mélanger des tenseurs de mauvaise forme avec d'autres tenseurs). |
| **Indexation sur tenseurs** | Si vous avez indexé sur une liste Python ou un tableau NumPy, c'est très similaire aux tenseurs, sauf qu'ils peuvent avoir beaucoup plus de dimensions. |
| **Mélanger les tenseurs PyTorch et NumPy** | PyTorch joue avec les tenseurs ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy aime les tableaux ([`np.ndarray`](https://numpy.org /doc/stable/reference/generated/numpy.ndarray.html)) parfois, vous souhaiterez les mélanger et les faire correspondre. |
| **Reproductibilité** | L'apprentissage automatique est très expérimental et comme il utilise beaucoup de *aléatoire* pour fonctionner, vous souhaiterez parfois que ce *aléatoire* ne soit pas si aléatoire. |
| **Exécution de tenseurs sur GPU** | Les GPU (Graphics Processing Units) rendent votre code plus rapide, PyTorch facilite l'exécution de votre code sur des GPU. |

## Où pouvez-vous documenter sur  Pytorch ou obtenir de l'aide ?

### TODO ajouter la documentation et video d'introduction de Pytorch

Il existe également les [forums des développeurs PyTorch](https://discuss.pytorch.org/), un endroit très utile pour tout ce qui concerne PyTorch.

## Importater PyTorch

> **Remarque :** Avant d'exécuter le code de ce notebook, vous devez avoir suivi les [étapes de configuration de PyTorch](https://pytorch.org/get-started/locally/).
>
> Cependant, **si vous utilisez Google Colab**, tout devrait fonctionner (Google Colab est livré avec PyTorch et d'autres bibliothèques installées).

Commençons par importer PyTorch et vérifier la version que nous utilisons.

In [9]:
import torch
torch.__version__

'2.3.0+cpu'

## Introduction aux tenseurs

Maintenant que PyTorch est importé, il est temps d'en apprendre davantage sur les tenseurs.

Les tenseurs sont l’élément fondamental de l’apprentissage automatique.

Leur travail consiste à représenter les données de manière numérique.

Par exemple, vous pouvez représenter une image sous forme de tenseur avec la forme « [3, 224, 224] », ce qui signifierait « [colour_channels, height, width] », car l'image a « 3 » canaux de couleur (rouge, vert, bleu), une hauteur de « 224 » pixels et une largeur de « 224 » pixels.

![exemple de passage d'une image d'entrée à une représentation tensorielle de l'image, l'image est décomposée en 3 canaux de couleur ainsi que des nombres pour représenter la hauteur et la largeur](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

Dans le langage tensoriel (le langage utilisé pour décrire les tenseurs), le tenseur aurait trois dimensions, une pour « colour_channels », « height » et « width ».

Mais nous prenons de l'avance. Apprenons d'abord quelques bases sur les tenseurs en les codant en pratique.

### Créer des tenseurs

Il existe toute une page de documentation dédiée à la classe [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) sur la documentation officiel de Pytorch.

Votre premier devoir consiste à [lire la documentation sur `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) pendant 10 minutes. Mais vous pourrez y revenir plus tard.

La première chose que nous allons créer est un **scalaire**.

Un scalaire est un nombre unique et, en termes tensoriels, c'est un tenseur de dimension nulle.

> **Remarque :** C'est une tendance pour ce cours. Nous nous concentrerons sur l'écriture de code spécifique. Mais souvent, je propose des exercices qui impliquent de lire et de se familiariser avec la documentation PyTorch. Car après tout, une fois ce cours terminé, vous aurez sans doute envie d’en savoir plus. Et la documentation est un endroit où vous vous retrouverez assez souvent.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Voyez comment ce qui précède a imprimé `tensor(7)` ?

Cela signifie que bien que « scalaire » soit un nombre unique, il est de type « torch.Tensor ».

Nous pouvons vérifier les dimensions d'un tenseur en utilisant l'attribut `ndim`.

In [3]:
scalar.ndim

0

Et si nous voulions récupérer le nombre du tenseur ?

Comme dans, le transformer de `torch.Tensor` en un entier Python ?

Pour ce faire, nous pouvons utiliser la méthode `item()`.

In [4]:
scalar.item()

7

D'accord, voyons maintenant un **vecteur**.

Un vecteur est un tenseur à dimension unique mais peut contenir plusieurs nombres.

À titre d'exemple, vous pourriez avoir un vecteur `[3, 2]` pour décrire `[chambres, salles de bains]` dans votre maison. Ou vous pourriez avoir `[3, 2, 2]` pour décrire `[chambres, salles de bains, salon]` dans votre maison.

La tendance importante ici est qu'un vecteur est flexible dans ce qu'il peut représenter (idem pour les tenseurs).

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Qu'est ce qu'on va trouver on terme de dimension d'un vecteur ?

In [6]:
vector.ndim

1

Vous pouvez connaître le nombre de dimensions d'un tenseur dans PyTorch par le nombre de crochets à l'extérieur (`[`) et vous n'avez besoin de compter qu'un seul côté.

Combien de crochets `vector` a-t-il ?

Un autre concept important pour les tenseurs est leur attribut `shape`. La forme vous indique comment les éléments à l'intérieur sont disposés.

Voyons la forme de `vector`:

In [7]:
vector.shape

torch.Size([2])

Ce qui précède renvoie `torch.Size([2])`, ce qui signifie que notre vecteur a la forme de `[2]`. Cela est dû aux deux éléments que nous avons placés entre crochets (`[7, 7]`).

Voyons maintenant pour une **matrice**.

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Les matrices sont une generalisation des vecteur d'une à deux dimension.



In [9]:
MATRIX.ndim

2

`MATRIX` a deux dimensions (Priere de compter le nombre de crochets à l'extérieur d'un côté pour s'assurer).

> Quelle « forme » pensez-vous qu'il aura ?

In [10]:
MATRIX.shape

torch.Size([2, 2])

Nous obtenons le résultat `torch.Size([2, 2])` car `MATRIX` est composé de deux éléments en hauteur et deux éléments en largeur.

Et si on créait un **tenseur** ?

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Je tiens à souligner que les tenseurs peuvent représenter presque tout type de donnée.

Celui que nous venons de créer pourrait être les chiffres de ventes d'un magasin de steak et de cotelette de boeuf.

![un simple tenseur dans des feuilles Google affichant le jour de la semaine, les ventes de steaks et les ventes de beurre d'amande](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

À votre avis, combien de dimensions a-t-il ? (indice : utilisez l'astuce de comptage des crochets)

In [15]:
TENSOR.ndim

3

la forme de `TENSOR` est

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

Très bien, il affiche `torch.Size([1, 3, 3])`.

Les dimensions vont de l’extérieur vers l’intérieur.

Cela signifie qu'il y a 1 dimension de 3 sur 3.

![exemple de différentes dimensions de tenseur](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-différent-tensor-dimensions.png)

> **Remarque :** Vous m'avez peut-être remarqué en utilisant des lettres minuscules pour « scalaire » et « vecteur » et des lettres majuscules pour « MATRIX » et « TENSOR ». C'était exprès. Dans la pratique, vous verrez souvent des scalaires et des vecteurs désignés par des lettres minuscules telles que « y » ou « a ». Et les matrices et les tenseurs désignés par des lettres majuscules telles que « *X* » ou « *W* ».

> Vous remarquerez peut-être également les noms de matrice et de tenseur utilisés de manière interchangeable. C'est courant. Puisque dans PyTorch, vous avez souvent affaire à des « torch.Tensor » (d'où le nom du tenseur), cependant, la forme et les dimensions de ce qu'il y a à l'intérieur dicteront ce qu'il est réellement.

Résumons.

| Nom | Qu'est-ce que c'est? | Nombre de dimensions | Inférieur ou supérieur (généralement/exemple) |
| ----- | ----- | ----- | ----- |
| **scalaire** | un seul numéro | 0 | (`a`) |
| **vecteur** | un nombre avec une direction (par exemple la vitesse du vent avec une direction) mais peut aussi avoir de nombreux autres nombres | 1 |  (`y`) |
| **matrice** | un tableau de nombres à 2 dimensions | 2 |  (`Q`) |
| **tenseur** | un tableau de nombres à n dimensions | int(*) | (`X`) |

![Tenseur de matrice vectorielle scalaire et à quoi ils ressemblent](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Tenseurs aléatoires

Nous avons établi que les tenseurs représentent une certaine forme de données.

Et les modèles d’apprentissage automatique tels que les réseaux de neurones manipulent, recherchent, et identifient des structures (***Pattern***)  au sein des tenseurs.

Mais lors de la création de modèles d'apprentissage automatique avec PyTorch, il est rare que vous créiez des tenseurs à la main (comme ce que nous faisons).

Au lieu de cela, un modèle d’apprentissage automatique commence souvent avec de grands tenseurs de nombres aléatoires et ajuste ces nombres aléatoires au fur et à mesure qu’il traite les données pour mieux les représenter.

De manière systématique, il s'agit de :

`Commencez avec des nombres aléatoires -> regardez les données -> mettez à jour les nombres aléatoires -> regardez les données -> mettez à jour les nombres aléatoires...`

En tant que data scientist, vous pouvez définir comment le modèle d'apprentissage automatique démarre (initialisation), examine les données (représentation) et met à jour (optimisation) ses nombres aléatoires.

Pour l'instant, voyons comment créer un tenseur de nombres aléatoires.

Nous pouvons faire usage de [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) et en passant le paramètre `size`.

In [18]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0984, 0.0094, 0.9214, 0.1687],
         [0.1996, 0.7544, 0.8329, 0.3541],
         [0.5482, 0.7073, 0.4868, 0.1314]]),
 torch.float32)

In [19]:
random_tensor.ndim

2

In [24]:
randtens = torch.rand(size=(3,4))
randtens

tensor([[0.9927, 0.4917, 0.4362, 0.7714],
        [0.0612, 0.8523, 0.9427, 0.7165],
        [0.0985, 0.8770, 0.2601, 0.8814]])

La flexibilité de `torch.rand()` est que nous pouvons ajuster la `taille` pour qu'elle soit ce que nous voulons.

Par exemple, disons que vous vouliez un tenseur aléatoire dans la forme d'image commune de `[224, 224, 3]` (`[hauteur, largeur, color_channels`]).

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Des zéros et des uns

Parfois, vous souhaiterez simplement remplir les tenseurs avec des zéros ou des uns.

Cela arrive souvent avec le masquage (comme masquer certaines valeurs d'un tenseur avec des zéros pour empêcher un modèle de deep learning de prendre en consideration ces valeurs dans la procedure d'entrainement).

Créons un tenseur plein de zéros avec [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

Encore une fois, le paramètre « size » entre en jeu.

In [17]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Nous pouvons faire la même chose pour créer un tenseur rempli de 1 en utilisant [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html)

---

In [18]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Création d'un range de tenseurs :

Parfois, vous souhaiterez peut-être une plage de nombres (`range`), telle que 1 à 10 ou 0 à 100.

Vous pouvez utiliser `torch.arange(start, end, step)` pour le faire.

Où:
* `start` = début du range (par exemple 0)
* `end` = fin du range (par exemple 10)
* `step` = le pas entre chaque valeur (par exemple 1)

> **Remarque :** En Python, vous pouvez utiliser le python native `range()`. Cependant, dans PyTorch, `torch.range()` est obsolète et peut afficher une erreur à l'avenir.

In [25]:
zero_to_ten_deprecated = torch.range(0, 10)

#utilisation recomendée
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

C:\Users\HP\AppData\Local\Temp\ipykernel_19976\1693756618.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
mytensor = torch.tensor([[
    torch.arange(start=0, end=10, step= 1).tolist(),
    torch.arange(start=10, end=20, step= 1).tolist()]
])
mytensor

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

Parfois, vous souhaiterez peut-être qu'un tenseur d'un certain type ait la même forme qu'un autre tenseur.

Par exemple, un tenseur composé uniquement de zéros avec la même forme qu'un tenseur précédent.

Pour ce faire, vous pouvez utiliser [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) ou [`torch.ones_like(input)`](https ://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) qui renvoient respectivement un tenseur rempli de zéros ou de uns de la même forme que « l'entrée ».

In [33]:
ten_zeros = torch.zeros_like(input=mytensor)
ten_zeros

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

### Types de données Tenseurs

Il existe de nombreux [types de données tenseurs disponibles dans PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Certains sont spécifiques au CPU et d’autres sont meilleurs pour le GPU.

Savoir lequel est lequel peut prendre un certain temps.

Généralement, si vous voyez « torch.cuda » n'importe où, le tenseur est utilisé pour le GPU (puisque les GPU Nvidia utilisent une boîte à outils informatique appelée CUDA).

Le type le plus courant (et généralement celui par défaut) est « torch.float32 » ou « torch.float ».

C'est ce qu'on appelle une « virgule flottante 32 bits ».

Mais il existe également des virgules flottantes 16 bits (`torch.float16` ou `torch.half`) et des virgules flottantes 64 bits (`torch.float64` ou `torch.double`).

Et pour rendre les choses encore plus confuses, il existe également des entiers de 8 bits, 16 bits, 32 bits et 64 bits.

Et plus encore !

> **Remarque :** Un entier est un nombre rond et plat comme « 7 » alors qu'un flottant a un nombre décimal « 7.0 ».

La raison de tout cela est liée à la **précision informatique**.

La précision est la quantité de détails utilisée pour décrire un nombre.

Plus la valeur de précision (8, 16, 32) est élevée, plus il y a de détails et donc de données utilisées pour exprimer un nombre.

Cela est important dans l'apprentissage profond et le calcul numérique, car vous effectuez tellement d'opérations que plus vous devez calculer en détail, plus vous augementer la complexité des calculs.

Ainsi, les types de données de précision inférieure sont généralement plus rapides à calculer, mais sacrifient certaines performances sur les métriques d'évaluation telles que la précision (plus rapides à calculer mais moins précises).

> **Ressources :**
   * Consultez la [documentation PyTorch pour une liste de tous les types de données tenseurs disponibles](https://pytorch.org/docs/stable/tensors.html#data-types).
   * Lisez la [page Wikipédia pour un aperçu de ce qu'est la précision en informatique](https://en.wikipedia.org/wiki/Precision_(computer_science)).

Voyons comment créer des tenseurs avec des types de données spécifiques. Nous pouvons le faire en utilisant le paramètre `dtype`.

In [34]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Outre que les problèmes de forme (les formes des tenseurs ne correspondent pas), deux des autres problèmes les plus courants que vous rencontrerez dans PyTorch sont les problèmes de type de données et de périphérique.

Par exemple, l'un des tenseurs est « torch.float32 » et l'autre est « torch.float16 » (PyTorch necessite souvent que les tenseurs aient le même format).

Ou bien l'un de vos tenseurs est sur le CPU et l'autre sur le GPU (PyTorch requiert que les calculs entre tenseurs soient sur le même appareil).

Pour l'instant, créons un tenseur avec `dtype=torch.float16`.

In [35]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [36]:
float_32_tensor+float_16_tensor # operation permise due au conversion implicite mais fortement déconseiller

tensor([ 6., 12., 18.])

## Obtenir des informations à partir des tenseurs

Une fois que vous avez créé des tenseurs (ou que quelqu'un d'autre ou un module PyTorch les a créés pour vous), vous souhaiterez peut-être en obtenir des informations.

Nous les avons déjà vus, mais trois des attributs les plus courants que vous voudrez découvrir sur les tenseurs sont :
* `shape` - quelle est la forme du tenseur ? (certaines opérations nécessitent des règles de forme spécifiques)
* `dtype` - dans quel type de données les éléments du tenseur sont-ils stockés ?
* `device` - sur quel appareil le tenseur est-il stocké ? (généralement GPU ou CPU)

Créons un tenseur aléatoire et découvrons des détails à ce sujet.

In [37]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"shape : {some_tensor.shape}")
print(f"dtype : {some_tensor.dtype}")
print(f"device: {some_tensor.device}")

tensor([[0.2421, 0.0883, 0.1793, 0.3778],
        [0.5022, 0.6661, 0.7132, 0.3792],
        [0.6801, 0.9651, 0.3184, 0.6965]])
shape : torch.Size([3, 4])
dtype : torch.float32
device: cpu


> **Remarque :** Lorsque vous rencontrez des problèmes dans PyTorch, il s'agit très souvent d'un problème lié à l'un des trois attributs ci-dessus. Alors, lorsque les messages d'erreur apparaissent, Pensez à faire un débuggage avec l'affichage précédent :
   * "*de quelle forme sont mes tenseurs ? de quel type de données sont-ils et où sont-ils stockés ? quelle forme, quel type de données, et où ?*"

## Manipulation des tenseurs (opérations tensorielles)

Dans le deep learning, les données (images, texte, vidéo, audio, structures protéiques, etc.) sont représentées sous forme de tenseurs.

Un modèle apprend à partir de ces tenseurs et en effectuant une série d'opérations (pouvant atteindre plus de +1M million) sur les tenseurs pour créer une représentation des modèles dans les données d'entrée.

Ces opérations sont souvent une combinaisons :
* Ajout
* Soustraction
* Multiplication/ Division (élément par élément)
* Multiplication matricielle


Bien sûr, il y en a quelques autres ici et là, mais ce sont les éléments de base des fonctions constituant les réseaux de neurones.

En empilant ces éléments de base de la bonne manière, vous pouvez créer les réseaux de neurones les plus sophistiqués.

### Opérations de base

Commençons par quelques-unes des opérations fondamentales, addition (`+`), soustraction (`-`), mutliplication (`*`).

Ils fonctionnent exactement comme vous le pensez.

In [38]:
tensor = torch.tensor([1, 2, 3])
tensor + 10 , tensor.shape

(tensor([11, 12, 13]), torch.Size([3]))

In [26]:
tensor * 10

tensor([10, 20, 30])

In [27]:
tensor

tensor([1, 2, 3])

In [28]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [29]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch a également un tas de fonctions intégrées comme [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (abréviation de multiplication) et [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) pour effectuer les opérations de base.

In [30]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [31]:
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like `*` instead of `torch.mul()`

In [32]:
print(tensor, "*", tensor," est égale à:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])  est égale à: tensor([1, 4, 9])


### La multiplication matricielle

L'une des opérations les plus courantes dans les algorithmes d'apprentissage automatique et d'apprentissage profond (comme les réseaux de neurones) est la [multiplication matricielle](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implémente la fonctionnalité de multiplication matricielle dans la méthode [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Les deux principales règles de multiplication matricielle à retenir sont :

1. Les **dimensions intérieures** doivent correspondre :
   * `(3, 2) @ (3, 2)` ne fonctionnera pas
   * `(2, 3) @ (3, 2)` fonctionnera
   * `(3, 2) @ (2, 3)` fonctionnera
2. La matrice résultante a la forme des **dimensions extérieures** :
  * `(2, 3) @ (3, 2)` -> `(2, 2)`
  * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Remarque :** "`@`" en Python est le symbole de la multiplication matricielle.

> **Ressource :** Vous pouvez voir toutes les règles de multiplication matricielle en utilisant `torch.matmul()` [dans la documentation PyTorch](https://pytorch.org/docs/stable/generated/torch.matmul. html).

Créons un tenseur et effectuons dessus une multiplication par éléments et une multiplication matricielle.

In [39]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

La différence entre la multiplication par éléments et la multiplication matricielle réside dans l'ajout de valeurs.

Pour notre variable `tensor` avec les valeurs `[1, 2, 3]` :

| Opération | Calcul | Codes |
| ----- | ----- | ----- |
| **Multiplication par éléments** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tenseur * tenseur` |
| **Multiplication matricielle** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tenseur)` |

In [42]:
tensor * tensor

tensor([1, 4, 9])

In [43]:
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
tensor @ tensor

tensor(14)

Vous pouvez effectuer une multiplication matricielle à la main, mais ce n'est pas recommandé.

La méthode intégrée `torch.matmul()` est plus rapide.

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 7 ms


tensor(14)

In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

## L'une des erreurs les plus courantes en deep learning (erreurs de forme)

Étant donné qu'une grande partie de l'apprentissage profond consiste à se multiplier et que l'exécution d'opérations sur des matrices et que les matrices ont une règle stricte quant aux formes et aux tailles qui peuvent être combinées, l'une des erreurs les plus courantes que vous rencontrerez dans l'apprentissage profond est l'inadéquation des formes.

In [48]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) #error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Nous pouvons faire fonctionner la multiplication matricielle entre `tensor_A` et `tensor_B` en faisant correspondre leurs dimensions intérieures.

L'une des façons de procéder consiste à utiliser une **transposition** (changer les dimensions d'un tenseur donné).

Vous pouvez effectuer des transpositions dans PyTorch en utilisant soit :
* `torch.transpose(input, dim0, dim1)` - où `input` est le tenseur souhaité à transposer et `dim0` et `dim1` sont les dimensions à permuter.
* `tensor.T` - où `tensor` est le tenseur que vous souhaitez transposer.

Essayons ce dernier.

In [49]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [50]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [51]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Il existe aussi la méthode [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) qui est un racourcis de `torch.matmul()`.

In [43]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Les réseaux de neurones sont formés par de multiplications matricielles et de produits scalaires.

Le module [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html), également connue sous le nom de couche feed-forward ou couche entièrement connectée, implémente une multiplication matricielle entre une entrée « x » et une matrice de pondération « A ».

$$
y = x\cdot{A^T} + b
$$

Où:
* `x` est l'entrée de la couche (le deep learning est une composition successive de couches comme `torch.nn.Linear()` et d'autres les unes suivis d'autres, etc...).
* `A` est la matrice de pondération  constituée de poids créée par la couche, cela commence par des nombres aléatoires qui sont ajustés à mesure qu'un réseau neuronal apprend à mieux représenter les modèles dans les données (remarquez le "`T`", c'est parce que la matrice de pondération est transposée ).
   * **Remarque :** Vous pouvez également souvent voir « X » ou une autre lettre comme « W » utilisée pour présenter la matrice de pondération pour designer les poids := weights.
* « b » est le terme de biais utilisé pour compenser légèrement les pondérations et les entrées.
* `y` est la sortie (une manipulation de l'entrée dans l'espoir d'y découvrir des modèles).


testons cette couche linéaire.

Essayez de changer les valeurs de « in_features » et « out_features » ci-dessous et voyez ce qui se passe.

Remarquez-vous quelque chose à voir avec les formes ?

In [44]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


> **Question :** Que se passe-t-il si vous modifiez « in_features » de 2 à 3 ci-dessus ? Est-ce une erreur ? Comment pourriez-vous changer la forme de l'entrée (`x`) pour vous adapter à l'erreur ? Indice : travaillons maintenant avec `tensor_B` au lieu de `tensor_A`.

### Trouver le min, le max, la moyenne, la somme, etc. (agrégation)

Maintenant que nous avons vu quelques façons de manipuler les tenseurs, passons en revue quelques façons de les agréger (passer de plus de valeurs à moins de valeurs).

Nous allons d’abord créer un tenseur, puis en trouver le maximum, le minimum, la moyenne et la somme.

In [45]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#print(f"Mean: {x.mean()}") # error
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Remarque :** Certaines méthodes telles que `torch.mean()` peuvent nécessiter
les tenseurs doivent être dans `torch.float32` (le plus courant) ou dans un autre type de données spécifique, sinon l'opération échouera.

Vous pouvez également faire la même chose que ci-dessus avec les méthodes « torch ».

In [49]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positionnement min/max

Vous pouvez également trouver l'indice d'un tenseur où existe le maximum ou le minimum avec [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) et [`torch .argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectivement.

Ceci est utile dans le cas où vous souhaitez simplement la position où se trouve la valeur la plus élevée (ou la plus basse) et non la valeur réelle elle-même (comme lors de l'utilisation de la [fonction d'activation softmax pour une classification multi-classe](https://pytorch.org /docs/stable/generated/torch.nn.Softmax.html)).

In [51]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Changer le type de données du tenseur

Comme mentionné, un problème courant avec les opérations d'apprentissage en profondeur est que vos tenseurs sont dans différents types de données.

Si un tenseur est codé sur `torch.float64` et un autre sur `torch.float32`, vous pourriez rencontrer des erreurs.

Mais il existe une solution.

Vous pouvez modifier les types de données des tenseurs en utilisant [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) où le `dtype` Le paramètre est le type de données que vous souhaitez utiliser.

Nous allons d'abord créer un tenseur et vérifier son type de données (la valeur par défaut est `torch.float32`).

In [52]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [53]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [54]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Remarque :** Différents types de données peuvent prêter à confusion au début. Mais pensez-y comme ceci : plus le nombre est bas (par exemple 32, 16, 8), moins un ordinateur stocke la valeur avec précision. Et avec une quantité de stockage inférieure, cela se traduit généralement par un calcul plus rapide et un modèle global plus petit. Les réseaux de neurones mobiles fonctionnent souvent avec des entiers de 8 bits, plus petits et plus rapides à exécuter, mais moins précis que leurs homologues float32. Pour en savoir plus à ce sujet, j'avais lu sur [la précision en informatique](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Exercice :** Jusqu'à présent, nous avons couvert pas mal de méthodes tensorielles, mais il y en a bien d'autres dans la [documentation `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) , je vous recommande de passer 10 minutes à faire défiler et à examiner ceux qui attirent votre attention. Cliquez dessus, puis écrivez-les vous-même en code pour voir ce qui se passe.

### Operations de : Reshaping, stacking, squeezing and unsqueezing

Souvent, vous souhaiterez remodeler ou modifier les dimensions de vos tenseurs sans réellement modifier les valeurs qu'ils contiennent.

Pour ce faire, certaines méthodes populaires sont :

| Méthode | Description en une ligne |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Remodèle `input` en `shape` (si compatible), peut également utiliser `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Renvoie une vue du tenseur d'origine sous une « forme » différente mais partage les mêmes données que le tenseur d'origine. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatène une séquence de « tenseurs » le long d'une nouvelle dimension (« dim »), tous les « tenseurs » doivent être de la même taille. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Presse « input » pour supprimer toutes les dimensions avec la valeur « 1 ». |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Renvoie « input » avec une valeur de dimension de « 1 » ajoutée à « dim ». |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Renvoie une *vue* de « l'entrée » d'origine avec ses dimensions permutées (réorganisées) en « dims ». |

Pourquoi faire tout cela ?

Parce que les modèles d'apprentissage profond (réseaux de neurones) consistent tous à manipuler les tenseurs d'une manière ou d'une autre. Et à cause des règles de multiplication matricielle, si vous avez des différences de forme, vous rencontrerez des erreurs. Ces méthodes vous aident à vous assurer que les opérations sur les éléments de vos tenseurs s'effectue correctement.

Essayons-les.

Tout d’abord, nous allons créer un tenseur.

In [55]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Ajout d'une seconde dimension au tenseur `x` avec  `torch.reshape()`.

In [56]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

We can also change the view with `torch.view()`.

In [58]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

N'oubliez pas cependant que changer la vue d'un tenseur avec `torch.view()` ne crée en réalité qu'une nouvelle vue du *même* tenseur.

Donc le fait de changer la vue change également le tenseur d'origine.

In [59]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Si nous voulions empiler notre nouveau tenseur sur lui-même cinq fois, nous pourrions le faire avec `torch.stack()`.

In [64]:
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Que diriez-vous de supprimer toutes les dimensions singulière d'un tenseur ?
Pour ce faire, vous pouvez utiliser `torch.squeeze()` (la signification de squeeze est de *presser* ou *compresser* le tenseur pour n'avoir que des dimensions supérieures ayant un nombre d'éléments > 1).

In [69]:
x_reshaped=x_reshaped.reshape(1, 1, 7)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[5., 2., 3., 4., 5., 6., 7.]]])
Previous shape: torch.Size([1, 1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Et pour faire l'inverse de `torch.squeeze()`, vous pouvez utiliser `torch.unsqueeze()` pour ajouter une valeur de dimension de 1 à un index spécifique.

In [70]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])



---

Les données sont souvent conduites aux réseaux de neurones sous forme de lot (petit ensemble d'une dixaine/centaines d'éléments). Un lot est généralement de taille (32, forme d'un élément ). Les deux opérations précédentes sont bénéfiques par exemple pour créer un lot de données à partir des éléments ou bien lors de l'évaluation d'une seule instance de donnée par les réseaux de neurones en la convertissant en un lot de taille (1, forme de l'élément).

Vous pouvez également réorganiser l'ordre des valeurs des axes avec `torch.permute(input, dims)`, où `input` est transformé en une *vue* avec de nouveaux `dims`.

In [71]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1) # permuter les axes dans l'ordre suivant: 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **Remarque** : Étant donné que la permutation renvoie une *vue* (partage les mêmes données que l'original), les valeurs du tenseur permuté seront les mêmes que le tenseur d'origine et si vous modifiez les valeurs dans la vue, ce sera le cas. modifier les valeurs de l'original.

## Operations d'Indexing (selection d'éléments de tenseurs)

Parfois, vous souhaiterez sélectionner des données spécifiques à partir des tenseurs (par exemple, uniquement la première colonne ou la deuxième ligne).

Pour ce faire, vous pouvez utiliser l'indexation.

Si vous avez déjà indexé sur des listes Python ou des tableaux NumPy, l'indexation dans PyTorch avec des tenseurs est très similaire.

In [73]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [74]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [75]:
x[:, 0]

tensor([[1, 2, 3]])

In [76]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [77]:
x[:, 1, 1]

tensor([5])

In [78]:
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch & NumPy

Étant donné que NumPy est une bibliothèque de calcul numérique Python populaire, PyTorch dispose de fonctionnalités permettant d'interagir correctement avec elle.

Les deux méthodes principales que vous souhaiterez utiliser pour NumPy vers PyTorch (et vice-versa) sont :
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - Tableau NumPy -> Tenseur PyTorch.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - Tenseur PyTorch -> Tableau NumPy.

Essayons-les.

In [79]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Remarque :** Par défaut, les tableaux NumPy sont créés avec le type de données « float64 » et si vous le convertissez en tenseur PyTorch, il conservera le même type de données (comme ci-dessus).
>
> Cependant, de nombreux calculs PyTorch utilisent par défaut `float32`.
>
> Donc, si vous souhaitez convertir votre tableau NumPy (float64) -> Tenseur PyTorch (float64) -> Tenseur PyTorch (float32), vous pouvez utiliser `tensor = torch.from_numpy(array).type(torch.float32)`.

Parce que nous avons réaffecté le `tensor` ci-dessus, si vous modifiez le tenseur, le tableau reste le même.

In [81]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

l'utilisation de `tensor.numpy()` est similaire :

In [82]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Et la même règle s'applique que ci-dessus, si vous modifiez le `tensor` d'origine, le nouveau `numpy_tensor` reste le même.

In [83]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductibilité (essayer d'enlever le hasard de l'aléatoire)

Au fur et à mesure que vous en apprendrez davantage sur les réseaux de neurones et l’apprentissage automatique, vous commencerez à découvrir à quel point le hasard joue un rôle.

Eh bien, c’est du pseudo-aléatoire. Parce qu'après tout, tels qu'ils sont conçus, un ordinateur est fondamentalement déterministe (chaque étape est prévisible), donc le caractère aléatoire qu'ils créent est un hasard simulé.

> Quel est alors le rapport avec les réseaux de neurones et l’apprentissage profond ?
>
> Nous avons discuté des réseaux de neurones en commençant par des nombres aléatoires pour representer les structures dans les données (ces nombres sont de mauvaises representations) en essaye donc à l'aide des algorithmes d'optimisations d'améliorer ces nombres aléatoires initiale en utilisant des opérations tensorielles pour mieux décrire les patterns des données.

En bref:

``commencez par des nombres aléatoires -> opérations tensorielles -> essayez de faire mieux``

Bien que le hasard soit agréable et puissant, on aimerait parfois qu'il y ait un peu moins de hasard.

Pourquoi?

Vous pouvez ainsi réaliser des expériences reproductibles.

Par exemple, vous créez un algorithme capable d’atteindre des performances X.

Et puis votre ami essaie pour vérifier la justesse des résultats.

Comment pourait-ils le faire d'une manière pareille ?

C'est là qu'intervient la **reproductibilité**.

En d’autres termes, pouvez-vous obtenir des résultats identiques (ou très similaires) sur votre ordinateur en exécutant le même code que le mien ?

Voyons un bref exemple de reproductibilité dans PyTorch.

Nous allons commencer par créer deux tenseurs aléatoires, puisqu'ils sont aléatoires, on s'attendrait à ce qu'ils soient différents, n'est-ce pas ?

In [84]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Comme vous vous en doutez peut-être, les tenseurs donnent des valeurs différentes.

Mais que se passe-t-il si vous souhaitez créer deux tenseurs aléatoires avec les *mêmes* valeurs.

Comme dans, les tenseurs contiendraient toujours des valeurs aléatoires mais ils auraient la même saveur.

C'est là qu'intervient [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html), où `seed` est un entier fixé
par l'utilisateur.

Essayons-le en créant d'autres tenseurs aléatoires.

In [85]:
import torch
import random


RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# reinitialisation du seed avec la meme instuction
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

> **Ressource :** Ce que nous venons de couvrir ne fait qu'effleurer la surface de la reproductibilité dans PyTorch. Pour en savoir plus, sur la reproductibilité en général et les `seed` aléatoires, consulter :
> * [La documentation de reproductibilité de PyTorch](https://pytorch.org/docs/stable/notes/randomness.html) (un bon exercice serait de le lire pendant 10 minutes et même si vous ne le comprenez pas maintenant, il est important d'en être conscient).
> * [La page sur les seed aléatoires de Wikipédia](https://en.wikipedia.org/wiki/Random_seed) (cela donnera un bon aperçu des seed générateurs aléatoires et du caractère pseudo-aléatoire en général).

## Utilisation des tenseurs sur GPUs

Les algorithmes d’apprentissage profond nécessitent de nombreuses opérations numériques.

Et par défaut ces opérations sont souvent effectuées sur un CPU (unité centrale de traitement).

Cependant, il existe un autre élément matériel courant appelé GPU (unité de traitement graphique), qui est souvent beaucoup plus rapide pour effectuer les types spécifiques d'opérations dont les réseaux neuronaux ont besoin (multiplications matricielles) que les processeurs.

Votre ordinateur en a peut-être un / sin non vous pouvez utiliser un gratuitement sur google colab.

Vous devriez envisager de l'utiliser chaque fois que vous le pouvez pour entraîner des réseaux de neurones, car il est probable que cela accélérera considérablement le temps d'entraînement.

Il existe plusieurs façons d’accéder d’abord à un GPU et ensuite de demander à PyTorch d’utiliser le GPU.

### 1. Obtenir un GPU

Il existe plusieurs façons d’obtenir un GPU.

| **Méthode** | **Difficulté à configurer** | **Avantages** | **Inconvénients** | **Comment configurer** |
| ----- | ----- | ----- | ----- | ----- |
| GoogleColab | Facile | Utilisation gratuite, presque aucune configuration requise, peut partager le travail avec d'autres aussi facilement qu'un lien | N'enregistre pas vos sorties de données, calcul limité, soumis à des délais d'attente | [Suivez le guide Google Colab](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Utilisez votre propre | Moyen | Exécutez tout localement sur votre propre machine | Les GPU ne sont pas gratuits et nécessitent un coût initial | Suivez les [Directives d'installation de PyTorch](https://pytorch.org/get-started/locally/) |
| Service Cloud (AWS, GCP, Azure) | Moyen-dur | Petit coût initial, accès à un calcul presque infini | Peut coûter cher s'il fonctionne en continu, la configuration prend un certain temps | Suivez les [Directives d'installation de PyTorch](https://pytorch.org/get-started/cloud-partners/) |

Il existe davantage d’options pour utiliser les GPU, mais les trois ci-dessus suffiront pour le moment.

Pour des expériences à petite échelle, une combinaison de Google Colab et de votre propre ordinateur sont largement suffisent.

> **Ressource :** Si vous souhaitez acheter votre propre GPU mais que vous ne savez pas quoi acheter, [Guide Pour ACHAT de GPU](https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/).

Pour vérifier si vous avez accès à un GPU Nvidia, vous pouvez exécuter `!nvidia-smi` où le `!` (également appelé bang) signifie « exécuter ceci sur la ligne de commande ».

In [88]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found




### 2. PyTorch et GPU

Une fois que vous disposez d'un GPU prêt à accéder, l'étape suivante consiste à utiliser PyTorch pour stocker des données (tenseurs) et calculer sur les données (effectuer des opérations sur des tenseurs).

Pour ce faire, vous pouvez utiliser le package [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html).

Vous pouvez tester si PyTorch a accès à un GPU en utilisant [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available ).

En utilisant Google Colab. Changer le runtime de votre environement en selectionant un GPU adequat voire T4 GPU. Documenter vous sur Google Colab afin de preparer votre premier notebook sur Colab.


In [2]:
# Check for GPU
import torch
torch.cuda.is_available()

True

Si ce qui précède renvoie « Vrai », PyTorch peut voir et utiliser le GPU, s'il renvoie « False », il ne peut pas voir le GPU et dans ce cas, vous devrez revenir sur les étapes d'installation.

Maintenant, disons que vous vouliez configurer votre code pour qu'il s'exécute sur le CPU *ou* le GPU s'il était disponible.

De cette façon, si vous ou quelqu'un décidez d'exécuter votre code, il fonctionnera quel que soit l'appareil qu'il utilise.

Créons une variable « device » pour stocker le type de périphérique disponible.

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Si le résultat ci-dessus `"cuda"`, cela signifie que nous pouvons configurer tout notre code PyTorch pour utiliser le périphérique CUDA disponible (un GPU) et s'il génère `"cpu"`, notre code PyTorch restera fidèle au CPU.

> **Remarque :** Dans PyTorch, il est recommandé d'écrire du [**code indépendant du périphérique**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). Cela signifie du code qui s'exécutera sur CPU (toujours disponible) ou GPU (si disponible).

Si vous souhaitez effectuer un calcul plus rapide, vous pouvez utiliser un GPU, mais si vous souhaitez effectuer un calcul *beaucoup* plus rapide, vous pouvez utiliser plusieurs GPU.

Vous pouvez compter le nombre de GPU auxquels PyTorch a accès en utilisant [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda. nombre_appareil).

In [5]:
torch.cuda.device_count()

1

Connaître le nombre de GPU auxquels PyTorch a accès est utile si vous souhaitez exécuter un processus spécifique sur un GPU et un autre processus sur un autre (PyTorch dispose également de fonctionnalités pour vous permettre d'exécuter un processus sur *tous* les GPU).

### 3. Mettre des tenseurs (et des modèles) sur le GPU

Vous pouvez placer des tenseurs (et des modèles de neurones) sur un appareil spécifique en appelant [`.to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to. html) sur eux. Où « device » est le périphérique cible auquel vous souhaitez que le tenseur (ou le modèle) aille.

Pourquoi faire ceci?

Les GPU offrent un calcul numérique beaucoup plus rapide que les CPU et si un GPU n'est pas disponible, en raison de notre **code indépendant du périphérique** (voir ci-dessus), il fonctionnera sur le CPU.

> **Remarque :** Mettre un tenseur sur GPU à l'aide de `to(device)` (par exemple `some_tensor.to(device)`) renvoie une copie de ce tenseur, par exemple le même tenseur sera sur CPU et GPU. Pour écraser les tenseurs, réaffectez-les :
>
> `some_tensor = some_tensor.to(device)`

Essayons de créer un tenseur et de le mettre sur le GPU (s'il est disponible).

In [6]:
tensor = torch.tensor([1, 2, 3])

# tensor sur CPU par defaut
print(tensor, tensor.device)

# deplacer vers le GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Si vous disposez d'un GPU, le resultat :
```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

Notez que le deuxième tenseur a `device='cuda:0'`, cela signifie qu'il est stocké sur le 0ème GPU disponible (les GPU sont indexés à 0, si deux GPU étaient disponibles, ils seraient `'cuda:0'` et `' cuda:1'` respectivement, jusqu'à ``cuda:n'`).



### 4. Retourner les tenseurs vers le CPU

Et si nous voulions ramener le tenseur vers le CPU ?

Par exemple, vous souhaiterez faire cela si vous souhaitez interagir avec vos tenseurs avec NumPy (NumPy n'exploite pas le GPU).

Essayons d'utiliser la méthode [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) sur notre `tensor_on_gpu`.

In [7]:
# si le tensor est sur GPU, on ne peut par le transformer en NumPy (Numpy = CPU uniquement)
tensor_on_gpu.numpy()

TypeError: ignored

Au lieu de cela, pour remettre un tenseur au CPU et utilisable avec NumPy, nous pouvons utiliser [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

Cela copie le tenseur dans la mémoire du processeur afin qu'il soit utilisable avec les processeurs.

In [8]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Ce qui précède renvoie une copie du tenseur GPU dans la mémoire CPU afin que le tenseur d'origine soit toujours sur le GPU.

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercices

Tous les exercices sont axés sur la pratique du code ci-dessus.

Vous devriez pouvoir les compléter en faisant référence à chaque section ou en suivant la ou les ressources liées.

***Ressources :***

1. Lecture de la documentation – Une grande partie de l'apprentissage en profondeur (et de l'apprentissage du code en général) consiste à se familiariser avec la documentation d'un certain framework que vous utilisez. Nous utiliserons beaucoup la documentation PyTorch tout au long du reste de ce cours.  Voir la documentation sur [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) et pour [`torch.cuda`](https://pytorch.org/ docs/master/notes/cuda.html#cuda-semantics).
2. Créez un tenseur aléatoire de forme « (7, 7) ».
3. Effectuez une multiplication matricielle sur le tenseur de 2 avec un autre tenseur aléatoire de forme `(1, 7)` (indice : vous devrez peut-être transposer le deuxième tenseur).
4. Réglez la valeur aléatoire sur « 0 » et refaites les exercices 2 et 3.
5. En parlant de seed aléatoires, nous avons vu comment les définir avec `torch.manual_seed()` mais existe-t-il un équivalent GPU ? (indice : vous devrez consulter la documentation de « torch.cuda » pour celui-ci). Si tel est le cas, définissez la valeur de départ aléatoire du GPU sur « 1234 ».
6. Créez deux tenseurs aléatoires de forme `(2, 3)` et envoyez-les tous les deux au GPU (vous aurez besoin d'accéder à un GPU pour cela). Définissez `torch.manual_seed(1234)` lors de la création des tenseurs (il n'est pas nécessaire que ce soit le seed aléatoire du GPU).
7. Effectuez une multiplication matricielle sur les tenseurs que vous avez créés en 6 (encore une fois, vous devrez peut-être ajuster les formes de l'un des tenseurs).
8. Trouvez les valeurs maximales et minimales de la sortie de 7.
9. Trouvez les valeurs d'index maximales et minimales de la sortie de 7.
10. Créez un tenseur aléatoire de forme « (1, 1, 1, 10) », puis créez un nouveau tenseur avec toutes les dimensions « 1 » supprimées pour laisser un tenseur de forme « (10) ». Réglez le seed sur « 7 » lorsque vous la créez et imprimez le premier tenseur et sa forme ainsi que le deuxième tenseur et sa forme.

## BoNuS

* Prenez une heure de votre temps pour explorer les tutoriels [PyTorch basics tutorial](https://pytorch.org/tutorials/beginner/basics/intro.html) (Consulter aussi la partie [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) and [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)).
* La section : [Introduction to PyTorch - YouTube Series](https://pytorch.org/tutorials/beginner/introyt.html) contient une revue de tous les notions basiques de Pytorch qu'on va voir dans ce module.